name: publish-release-archive
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set modified times
        uses: greatness7/action-set-mtime@v1
        with:
          times: |
            "**/OAAB_Data.esm" = 1577854800

      - name: create release archive
        shell: bash
        run: 7z a OAAB_Data.7z . '-xr!*.git*' '-x!## *' '-xr!workflow'

      - name: publish to nexusmods
        uses: greatness7/nexusmods_file_updater@v2
        with:
          username: ${{secrets.NEXUS_USERNAME}}
          password: ${{secrets.NEXUS_PASSWORD}}
          game_domain_name: "morrowind"
          mod_id: "49042"
          file_name: "OAAB_Data"
          file_version: ${{github.ref_name}}
          update_version: true
          file_category: "Main Files"
          new_existing_version: true
          original_file: "^OAAB_Data .*"
          remove_old_version: true
          file_description: "[url=https://github.com/of-ash-and-blight/oaab-data/discussions/categories/announcements]dev blog[/url]"
          remove_nmm_button: false
          set_as_main_nmm: true
          requirements_pop_up: true
          file_path: "./OAAB_Data.7z"
