name: publish-release-archive
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set modified times
        uses: greatness7/action-set-mtime@v1
        with:
          times: |
            "**/OAAB_Data.esm" = 1577854800

      - name: create release archive
        shell: bash
        run: 7z a OAAB_Data.7z . '-xr!*.git*' '-x!## *' '-xr!workflow' '-xr!Developer Tools' '-xr!OAAB_Data-HD'

      - name: upload release archive
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: OAAB_Data.7z